CREATE TABLE "run_lead" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" text NOT NULL,
	"niche" text NOT NULL,
	"placeId" text NOT NULL,
	"businessName" text NOT NULL,
	"address" text,
	"phoneDisplay" text,
	"phoneDigits" text,
	"websiteUrl" text,
	"socialLink" text,
	"socialPlatform" text,
	"classification" text NOT NULL,
	"businessStatus" text,
	"isLikelyChain" boolean DEFAULT false NOT NULL,
	"googleMapsUrl" text,
	"rating" double precision,
	"totalReviews" integer,
	"firstSeenAt" timestamp DEFAULT now() NOT NULL,
	"lastSeenAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "run_lead_user_niche_place_unique" UNIQUE("userId","niche","placeId")
);
--> statement-breakpoint
CREATE TABLE "scrape_run" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" text NOT NULL,
	"niche" text NOT NULL,
	"campaignMode" text NOT NULL,
	"locationLabel" text NOT NULL,
	"isMapClickBasedLocation" boolean DEFAULT false NOT NULL,
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"radiusKm" integer NOT NULL,
	"targetCount" integer NOT NULL,
	"status" text NOT NULL,
	"stopReason" text,
	"currentPhase" text,
	"currentTerm" text,
	"discoveredCount" integer DEFAULT 0 NOT NULL,
	"matchingLeadCount" integer DEFAULT 0 NOT NULL,
	"duplicatesSkipped" integer DEFAULT 0 NOT NULL,
	"discoveryCallCount" integer DEFAULT 0 NOT NULL,
	"detailsCallCount" integer DEFAULT 0 NOT NULL,
	"cancelRequested" boolean DEFAULT false NOT NULL,
	"errorMessage" text,
	"startedAt" timestamp DEFAULT now() NOT NULL,
	"completedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "run_lead_snapshot" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"runId" uuid NOT NULL,
	"leadId" uuid NOT NULL,
	"placeId" text NOT NULL,
	"niche" text NOT NULL,
	"businessName" text NOT NULL,
	"businessNameNormalized" text,
	"addressDisplay" text,
	"addressNormalized" text,
	"phoneDisplay" text,
	"phoneDigits" text,
	"websiteUrl" text,
	"socialLink" text,
	"socialPlatform" text,
	"classification" text NOT NULL,
	"matchReason" text NOT NULL,
	"inclusionBasis" text NOT NULL,
	"hasPhone" boolean DEFAULT false NOT NULL,
	"hasRealWebsite" boolean DEFAULT false NOT NULL,
	"hasSocialLink" boolean DEFAULT false NOT NULL,
	"isSocialOnly" boolean DEFAULT false NOT NULL,
	"isLikelyChain" boolean DEFAULT false NOT NULL,
	"businessStatus" text,
	"isStatusUncertain" boolean DEFAULT false NOT NULL,
	"rating" double precision,
	"totalReviews" integer,
	"googleMapsUrl" text,
	"matched" boolean NOT NULL,
	"rank" integer,
	"firstDiscoveryMode" text,
	"firstDiscoveryTerm" text,
	"firstDiscoveryStage" text,
	"isMultiPathDiscovered" boolean DEFAULT false NOT NULL,
	"distinctDiscoveryPathCount" integer DEFAULT 1 NOT NULL,
	"hadDetailsRetry" boolean DEFAULT false NOT NULL,
	"detailsAttemptCount" integer DEFAULT 1 NOT NULL,
	"detailsSucceededAt" timestamp NOT NULL,
	"isFirstTimeSeenInSystem" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "run_lead" ADD CONSTRAINT "run_lead_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scrape_run" ADD CONSTRAINT "scrape_run_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "run_lead_snapshot" ADD CONSTRAINT "run_lead_snapshot_runId_scrape_run_id_fk" FOREIGN KEY ("runId") REFERENCES "public"."scrape_run"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "run_lead_snapshot" ADD CONSTRAINT "run_lead_snapshot_leadId_run_lead_id_fk" FOREIGN KEY ("leadId") REFERENCES "public"."run_lead"("id") ON DELETE cascade ON UPDATE no action;
